language: java

sudo: required

dist: trusty

install: true

cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

before_script:
    - ./gradlew --version

script:
    - TERM=dumb ./gradlew build --scan

jdk:
    - oraclejdk11
